### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Eureka"

### ISSUE THREAD

**Issue by Kracter56** [EurekaCommunity/GenericPasswordRow#28]
Hello,

I wanted to integrate GenericPasswordRow to my project, but cocoapods
displays this message : 

`[!] CocoaPods could not find compatible versions for pod "Eureka":
  In snapshot (Podfile.lock):
    Eureka (= 5.2.1, ~> 5.0)

  In Podfile:
    Eureka

    GenericPasswordRow was resolved to 1.0.0, which depends on
      Eureka (~> 1.7)
`

Could you please update the project to the latest Eureka framework version 5.2.1 please ? 

I cannot update myself, because I'm a beginner.

Thank you in advance.

**Comment by mats-claassen** [comment]
Hi sorry for the late reply. There is a problem with your Podfile as `GenericPasswordRow was resolved to 1.0.0` while the latest version is 3.0.0. You should make sure to use the latest version. Also run a `pod repo update` before installing the pod.

**Comment by tejassharma96** [comment]
Hi, this is still an issue when setting the version to 3.0

Podfile excerpt: 
```podfile
pod 'Eureka', '~> 5.2'
pod 'GenericPasswordRow', '~> 3.0'
```

Error message (this is from running `pod update` after a `pod repo update`, but `pod install` gives the same output):
```
$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Eureka":
  In Podfile:
    Eureka (~> 5.2)

    GenericPasswordRow (~> 3.0) was resolved to 3.0.0, which depends on
      Eureka (~> 4.0)

Specs satisfying the `Eureka (~> 5.2), Eureka (~> 4.0)` dependency were found, but they required a higher minimum deployment target.
```

I suspect the tag may not have been set correctly

**Comment by tejassharma96** [comment]
As I suspected, this is indeed the case: https://github.com/EurekaCommunity/GenericPasswordRow/releases/tag/3.0.0

Could you please update the version as soon as possible.

**Comment by mats-claassen** [comment]
Oh I see. My bad. We should have created a new release. You could use master branch until we get a release

**Comment by mats-claassen** [comment]
🚀  GenericPasswordRow (3.1.0) successfully published

**Comment by Kracter56** [comment]
I had the issue after the latest update. Thank you I will test when the new update will be released.

**Comment by tejassharma96** [comment]
Confirmed that it now works, thanks!
